### ISSUE TITLE
evolvio4all.github.io website outdated

### ISSUE THREAD

**Issue by UnknownEvil** [evolvio4all/evolvio4JavaScript#16]
@evolvio4all the github site is outdated and I'd like it if you could make it update automatically OR just updated it every so often manually.

**Comment by UnknownEvil** [comment]
I made a pull request

**Comment by winnie334** [comment]
That's indeed kinda weird, normally if the github page hosts the index.html file it should update automatically. Perhaps some setting is off?

**Comment by UnknownEvil** [comment]
There's actually just a repository for it (see https://github.com/evolvio4all/evolvio4all.github.io) I made a pull request but I don't have write access

**Comment by winnie334** [comment]
Huh, strange! Normally you can create a github page right from the same repository, meaning it'll always stay up to date. Also, I'm kinda confused - you made all of this by yourself yet it isn't your repository?

**Comment by UnknownEvil** [comment]
@winnie334 It is not my repository, I _believe_ https://github.com/NateUniAccount is the account holder. I have write access to _this_ repository, however, I don't have write access to the repository he made for the website. I'm pretty sure they made a new repository as the website because when the other versions of evolv.io potentially get fleshed out, we'll need to be able to include them somewhere.

**Comment by winnie334** [comment]
May I ask why you are using this repository then? I can't think of a good reason of using someone else's repo if that person isn't even contributing himself. If I was in your shoes i'd have made my own repo a long time ago :) More control is always useful.

But then again, maybe I wouldn't have found this project if it weren't for that one comment deep in the comment section linking to here.  I'm glad I found it though :)

**Comment by winnie334** [comment]
Oh okay, I was just wondering! :) 
Trying to learn the situation here.
(But still, it would be handy if this repo had its own github page ^^)

**Comment by UnknownEvil** [comment]
You're very right

**Comment by NateUniAccount** [comment]
Heya, just to confirm I made the evolvio4all account. I'd love to be able to contribute more but with work and my other projects I just haven't got the time for the foreseeable future :( I check in every now and then but that's all I have time for. Am happy to hand the account over if there's anyone who has more time for it and wants to take it over.

**Comment by UnknownEvil** [comment]
I have all the time in the world, but I'm not confident in my moderation skills. I'm sure nothing catastrophic would go wrong, but I wouldn't want to be blamed if anything did. :P

**Comment by UnknownEvil** [comment]
Since I've updated the link to my website, I'm going to close this.
