### ISSUE TITLE
Huge performance sink I was unaware of

### ISSUE THREAD

**Issue by UnknownEvil** [evolvio4all/evolvio4JavaScript#24]
![JSPerf](https://puu.sh/BOINy/bb510fae05.png)

**Comment by winnie334** [comment]
I don't really understand - don't all these code snippets simply return the last element of the array?

**Comment by UnknownEvil** [comment]
This is a website called jsPerf, this is the array that I'm using. ![array](https://puu.sh/BOIR5/0527b7b5fc.png)

The website tests how fast each one operates and as you can see, the slowest method is the one getting used the most (since there are about 15,000 - 25,000 tiles). This is a huge problem for performance and probably why you had to reduce map size in the first place.

They all perform the same basic operation.

**Comment by winnie334** [comment]
Interesting discovery, I did not know about this either.

But for maximum performance improvement, something should change fundamentally about the `feedForward` function in brain.js. It is a quadruple-nested for loop and is, according to chrome, responsible for 70% of the time spent processing.

Of course, this is not my expertise. I have no idea how the brain exactly works. There might not even be a single improvement possible in this function (I strongly doubt this though). But, it would have a _huge_ impact on performance if even the smallest optimization was found in the most inner loop.

I'm happy you're looking into this though, better performance means faster calculating which results in longer evolution :)

**Comment by winnie334** [comment]
>this is probably the most expensive thing in the code

I just tested it and in the short timeframe I recorded, the code you showed took 13 milliseconds in total to run (0.8% of cpu usage). Compare that to other expensive functions such as feedForward, who took 2536 milliseconds, or 68% of the cpu time. Of course, it is slightly more complex, but I think it is a wrong assumption to blame the tile update for the performance sink.

**Comment by UnknownEvil** [comment]
I am well aware the feedForward function is the single most expensive function in terms of processing time,  It did contain the of problem but in the most recent commit I have fixed it.

**Comment by winnie334** [comment]
Alright, I was just mentioning it so you don't focus too much on that small snippet of code :)

It would be great if we could improve some of those fundamental functions though.

**Comment by UnknownEvil** [comment]
I do think we should split the update function into more functions so we can profile it better

**Comment by winnie334** [comment]
Yep, exactly my thoughts. Personally I have split it up in doSeasonStuff() and doCreateStuff(), but it isn't really worth it making a pull request for that. Perhaps you can also split up the creature stuff even more, since it is quite long on itself.

**Comment by UnknownEvil** [comment]
It is already pretty clear that feedForward is the most expensive function by far, maybe there is something we could do to make it faster?

**Comment by winnie334** [comment]
Well, you know what's happening there! But honestly, calculating _each_ node with _every_ weight for _every_ LSTM for _every_ creature, **_every single frame_**, sounds pretty costly on itself. Of course there might be some simple things you can do (decrease the number of inputs, give a lower score to larger networks do discourage thousands of nodes, etc) but I wouldn't know what fundamental design changes you could make to improve the performance.

**Comment by UnknownEvil** [comment]
Alright, so the only factor of brain size even a little out of my control is determined by the number of eyes. However, I can even limit this by limiting the number of eyes. If you'd look at the current version you'll see I just implemented a method to double creature.feedForward's execution speed

**Comment by UnknownEvil** [comment]
Uhhh, could you look and check and see what the autoMode calculates for you? Mine is about 30 - 35 at 50 population

**Comment by UnknownEvil** [comment]
Since this specific issue has been fixed, I'm closing this.

**Comment by NateUniAccount** [comment]
Found a *potential* improvements that *might* work. Please note I've not even tried them so don't hold your breath lol

The Creature.feedForward method uses the Math.tanh() function and someone made a [fast approximation method](https://stackoverflow.com/questions/6118028/fast-hyperbolic-tangent-approximation-in-javascript) that might be worth looking at. I tried looking for a fast approximation for Math.exp() but couldn't find any apart from some really heavy mathy stuff to do with Taylor series expansion.

There was also some interesting performance stuff about [typed arrays](https://stackoverflow.com/questions/24853686/javascript-typedarray-performance) but that was less clear.

**Comment by NateUniAccount** [comment]
There's a [jsperf test here](https://jsperf.com/loop-array-classic-vs-object) that loops a classic array vs a `new Array(n)` that suggests they have basically the same performance

**Comment by NateUniAccount** [comment]
Another idea to improve performance might be to only render a strip of the tiles on each tick. The colour doesn't change a great deal so it won't be noticeable unless a creature dies on a tile the user is looking at.
The only awkward thing would be that any tiles with a creature even partially over it would still need rendering.
I bet it could reduce the time significantly if say only a quarter of the tiles were drawn per tick.

**Comment by UnknownEvil** [comment]
The main problem isn't with rendering (as it only happens once each loop, no matter the timescale).
The main issue is the update function (which isn't even that bad) because it gets updated timescale times, so, if it were 100x timescale it'd run update 100 times and render would still run once. My goal is to make it so the update can run as many times as possible in 50ms. Right now I get about 30x-40x in 50ms (without fast tanh) but I'm sure we can do a little better at least.

**Comment by UnknownEvil** [comment]
Compare: https://jsperf.com/loop-array-classic-vs-object/1
with: https://jsperf.com/loop-array-classic-vs-object/2

Classic is about 2% to 8% slower if the values aren't initialized. However, object notation is slower if the values are initialized as 0.
