### ISSUE TITLE
I have an idea

### ISSUE THREAD

**Issue by UnknownEvil** [evolvio4all/evolvio4JavaScript#29]
I'm thinking, what if we had a NN (neural network) that can have memories, but not like the LSTM (Long Short Term Memory) kind, we need some sort of RLTM (Real Long Term Memory [made up by me... I think]). I'm thinking a method we could use to achieve this is to make an array that a separate Neural Network can modify by outputting 2 values: index, and value. Using these we could replace the old value at array[index] with the newly output value. The LSTM would be able to use these memory values as inputs — in some way, and in theory. I plan to do this in a simpler project as a test.

**Comment by UnknownEvil** [comment]
Still need to work on this.

**Comment by UnknownEvil** [comment]
This is actually almost entirely working. I just need to work on some small bugs

**Comment by winnie334** [comment]
Very exciting stuff, I'm looking forward to seeing it in action!

**Comment by UnknownEvil** [comment]
Here is a picture of what I have in mind
![brainTheory](https://user-images.githubusercontent.com/12143899/72117833-1f467200-331d-11ea-8a21-b2a1811358d7.png)

**Comment by UnknownEvil** [comment]
This is not really an issue so I will close this for now
