### ISSUE TITLE
UPDATE: I tried GRU (Gated Recurring Units)

### ISSUE THREAD

**Issue by Air1N** [evolvio4all/evolvio4JavaScript#39]
It didn't work as well for this application, reverted back to LSTM

**Comment by winnie334** [comment]
Alright, good to hear you're still working on it! :)

**Comment by Air1N** [comment]
@winnie334 Always good to hear from someone else on this project, sucks I'm the only one with time to contribute I guess

**Comment by winnie334** [comment]
Yeah, sorry I haven't been active... ever. University gets in the way all year long, however if I wanted to I could probably find some time in between. Learning all of the source code seems a kinda daunting task though. :p

Regardless, I'm very happy the project is still developing! Keep it up~

**Comment by Air1N** [comment]
@winnie334 I hope to simplify some of the code

**Comment by Air1N** [comment]
Aight this was just an update, closing
